package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA



/**
 * Administradormaster generated by hbm2java
 */
public class Administradormaster  implements java.io.Serializable {


     private Integer idAdministradorMaster;
     private Miembrofisico miembrofisico;

    public Administradormaster() {
    }

    public Administradormaster(Miembrofisico miembrofisico) {
       this.miembrofisico = miembrofisico;
    }
   
    public Integer getIdAdministradorMaster() {
        return this.idAdministradorMaster;
    }
    
    public void setIdAdministradorMaster(Integer idAdministradorMaster) {
        this.idAdministradorMaster = idAdministradorMaster;
    }
    public Miembrofisico getMiembrofisico() {
        return this.miembrofisico;
    }
    
    public void setMiembrofisico(Miembrofisico miembrofisico) {
        this.miembrofisico = miembrofisico;
    }




}


