package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Agrupacionpersonas generated by hbm2java
 */
public class Agrupacionpersonas  implements java.io.Serializable {


     private Integer idAgrupacionPersonas;
     private String nombre;
     private Set<Miembrofisico> miembrofisicos = new HashSet<Miembrofisico>(0);
     private Set<Personamoral> personamorals = new HashSet<Personamoral>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public Agrupacionpersonas() {
    }

	
    public Agrupacionpersonas(String nombre) {
        this.nombre = nombre;
    }
    public Agrupacionpersonas(String nombre, Set<Miembrofisico> miembrofisicos, Set<Personamoral> personamorals, Set<Empresa> empresas) {
       this.nombre = nombre;
       this.miembrofisicos = miembrofisicos;
       this.personamorals = personamorals;
       this.empresas = empresas;
    }
   
    public Integer getIdAgrupacionPersonas() {
        return this.idAgrupacionPersonas;
    }
    
    public void setIdAgrupacionPersonas(Integer idAgrupacionPersonas) {
        this.idAgrupacionPersonas = idAgrupacionPersonas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Miembrofisico> getMiembrofisicos() {
        return this.miembrofisicos;
    }
    
    public void setMiembrofisicos(Set<Miembrofisico> miembrofisicos) {
        this.miembrofisicos = miembrofisicos;
    }
    public Set<Personamoral> getPersonamorals() {
        return this.personamorals;
    }
    
    public void setPersonamorals(Set<Personamoral> personamorals) {
        this.personamorals = personamorals;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }




}


