package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Chofer generated by hbm2java
 */
public class Chofer  implements java.io.Serializable {


     private int idChofer;
     private Miembrofisico miembrofisico;
     private Set<Licenciaconducir> licenciaconducirs = new HashSet<Licenciaconducir>(0);

    public Chofer() {
    }

	
    public Chofer(int idChofer, Miembrofisico miembrofisico) {
        this.idChofer = idChofer;
        this.miembrofisico = miembrofisico;
    }
    public Chofer(int idChofer, Miembrofisico miembrofisico, Set<Licenciaconducir> licenciaconducirs) {
       this.idChofer = idChofer;
       this.miembrofisico = miembrofisico;
       this.licenciaconducirs = licenciaconducirs;
    }
   
    public int getIdChofer() {
        return this.idChofer;
    }
    
    public void setIdChofer(int idChofer) {
        this.idChofer = idChofer;
    }
    public Miembrofisico getMiembrofisico() {
        return this.miembrofisico;
    }
    
    public void setMiembrofisico(Miembrofisico miembrofisico) {
        this.miembrofisico = miembrofisico;
    }
    public Set<Licenciaconducir> getLicenciaconducirs() {
        return this.licenciaconducirs;
    }
    
    public void setLicenciaconducirs(Set<Licenciaconducir> licenciaconducirs) {
        this.licenciaconducirs = licenciaconducirs;
    }




}


