package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private int idCiudad;
     private Estado estado;
     private String clave;
     private String nombre;
     private Set<Colonia> colonias = new HashSet<Colonia>(0);

    public Ciudad() {
    }

	
    public Ciudad(int idCiudad, Estado estado) {
        this.idCiudad = idCiudad;
        this.estado = estado;
    }
    public Ciudad(int idCiudad, Estado estado, String clave, String nombre, Set<Colonia> colonias) {
       this.idCiudad = idCiudad;
       this.estado = estado;
       this.clave = clave;
       this.nombre = nombre;
       this.colonias = colonias;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Colonia> getColonias() {
        return this.colonias;
    }
    
    public void setColonias(Set<Colonia> colonias) {
        this.colonias = colonias;
    }




}


