package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA



/**
 * Concecionario generated by hbm2java
 */
public class Concecionario  implements java.io.Serializable {


     private int idConcecionario;
     private Miembrofisico miembrofisico;

    public Concecionario() {
    }

    public Concecionario(int idConcecionario, Miembrofisico miembrofisico) {
       this.idConcecionario = idConcecionario;
       this.miembrofisico = miembrofisico;
    }
   
    public int getIdConcecionario() {
        return this.idConcecionario;
    }
    
    public void setIdConcecionario(int idConcecionario) {
        this.idConcecionario = idConcecionario;
    }
    public Miembrofisico getMiembrofisico() {
        return this.miembrofisico;
    }
    
    public void setMiembrofisico(Miembrofisico miembrofisico) {
        this.miembrofisico = miembrofisico;
    }




}


