package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

/**
 * Direccion generated by hbm2java
 */
public class Direccion implements java.io.Serializable
{

	private int idDireccion;
	private Estado estado;
	private Entidad entidad;
	private Tipodireccion tipodireccion;
	private String calle;
	private String numeroExterior;
	private String numeroInterior;
	private String codigoPostal;
	private String ciudadDelegacionMunicipio;
	private String colonia;
	private String comentario;

	public Direccion()
	{
	}

	public Direccion(int idDireccion, Estado estado, Entidad entidad, Tipodireccion tipodireccion)
	{
		this.idDireccion = idDireccion;
		this.estado = estado;
		this.entidad = entidad;
		this.tipodireccion = tipodireccion;
	}

	public Direccion(int idDireccion, Estado estado, Entidad entidad, Tipodireccion tipodireccion, String calle, String numeroExterior, String numeroInterior, String codigoPostal, String ciudadDelegacionMunicipio, String colonia, String comentario)
	{
		this.idDireccion = idDireccion;
		this.estado = estado;
		this.entidad = entidad;
		this.tipodireccion = tipodireccion;
		this.calle = calle;
		this.numeroExterior = numeroExterior;
		this.numeroInterior = numeroInterior;
		this.codigoPostal = codigoPostal;
		this.ciudadDelegacionMunicipio = ciudadDelegacionMunicipio;
		this.colonia = colonia;
		this.comentario = comentario;
	}

	public int getIdDireccion()
	{
		return this.idDireccion;
	}

	public void setIdDireccion(int idDireccion)
	{
		this.idDireccion = idDireccion;
	}

	public Estado getEstado()
	{
		return this.estado;
	}

	public void setEstado(Estado estado)
	{
		this.estado = estado;
	}

	public Entidad getEntidad()
	{
		return this.entidad;
	}

	public void setEntidad(Entidad entidad)
	{
		this.entidad = entidad;
	}

	public Tipodireccion getTipodireccion()
	{
		return this.tipodireccion;
	}

	public void setTipodireccion(Tipodireccion tipodireccion)
	{
		this.tipodireccion = tipodireccion;
	}

	public String getCalle()
	{
		return this.calle;
	}

	public void setCalle(String calle)
	{
		this.calle = calle;
	}

	public String getNumeroExterior()
	{
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior)
	{
		this.numeroExterior = numeroExterior;
	}

	public String getNumeroInterior()
	{
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior)
	{
		this.numeroInterior = numeroInterior;
	}

	public String getCodigoPostal()
	{
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal)
	{
		this.codigoPostal = codigoPostal;
	}

	public String getCiudadDelegacionMunicipio()
	{
		return this.ciudadDelegacionMunicipio;
	}

	public void setCiudadDelegacionMunicipio(String ciudadDelegacionMunicipio)
	{
		this.ciudadDelegacionMunicipio = ciudadDelegacionMunicipio;
	}

	public String getColonia()
	{
		return this.colonia;
	}

	public void setColonia(String colonia)
	{
		this.colonia = colonia;
	}

	public String getComentario()
	{
		return this.comentario;
	}

	public void setComentario(String comentario)
	{
		this.comentario = comentario;
	}
}
