package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA



/**
 * Empresaruta generated by hbm2java
 */
public class Empresaruta  implements java.io.Serializable {


     private int idEmpresaRuta;
     private Empresa empresa;
     private String nombre;

    public Empresaruta() {
    }

    public Empresaruta(int idEmpresaRuta, Empresa empresa, String nombre) {
       this.idEmpresaRuta = idEmpresaRuta;
       this.empresa = empresa;
       this.nombre = nombre;
    }
   
    public int getIdEmpresaRuta() {
        return this.idEmpresaRuta;
    }
    
    public void setIdEmpresaRuta(int idEmpresaRuta) {
        this.idEmpresaRuta = idEmpresaRuta;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


