package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Entidad generated by hbm2java
 */
public class Entidad implements java.io.Serializable
{

	private Integer idEntidad;
	private String rfc;
	private Set<Telefono> telefonos = new HashSet<Telefono>(0);
	private Set<Direccion> direccions = new HashSet<Direccion>(0);
	private Set<Archivo> archivos = new HashSet<Archivo>(0);
	private Personafisica personafisica;
	private Personamoral personamoral;

	public Entidad()
	{
	}

	public Entidad(String rfc, Set<Telefono> telefonos, Set<Direccion> direccions, Personafisica personafisica, Personamoral personamoral, Set<Archivo> archivos)
	{
		this.rfc = rfc;
		this.telefonos = telefonos;
		this.direccions = direccions;
		this.personafisica = personafisica;
		this.personamoral = personamoral;
		this.archivos = archivos;
	}

	public Integer getIdEntidad()
	{
		return this.idEntidad;
	}

	public void setIdEntidad(Integer idEntidad)
	{
		this.idEntidad = idEntidad;
	}

	public String getRfc()
	{
		return this.rfc;
	}

	public void setRfc(String rfc)
	{
		this.rfc = rfc;
	}

	public Set<Telefono> getTelefonos()
	{
		return this.telefonos;
	}

	public void setTelefonos(Set<Telefono> telefonos)
	{
		this.telefonos = telefonos;
	}

	public Set<Direccion> getDireccions()
	{
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions)
	{
		this.direccions = direccions;
	}

	public Personafisica getPersonafisica()
	{
		return this.personafisica;
	}

	public void setPersonafisica(Personafisica personafisica)
	{
		this.personafisica = personafisica;
	}

	public Personamoral getPersonamoral()
	{
		return this.personamoral;
	}

	public void setPersonamoral(Personamoral personamoral)
	{
		this.personamoral = personamoral;
	}

	public Set<Archivo> getArchivos()
	{
		return this.archivos;
	}

	public void setArchivos(Set<Archivo> archivos)
	{
		this.archivos = archivos;
	}
}
