package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private int idEstado;
     private Pais pais;
     private String clave;
     private String nombre;
     private String abreviatura;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);
     private Set<Ciudad> ciudads = new HashSet<Ciudad>(0);

    public Estado() {
    }

	
    public Estado(int idEstado, Pais pais) {
        this.idEstado = idEstado;
        this.pais = pais;
    }
	
    public Estado(int idEstado, Pais pais, String clave, String nombre, String abreviatura, Set<Direccion> direccions, Set<Ciudad> ciudads) {
       this.idEstado = idEstado;
       this.pais = pais;
       this.clave = clave;
       this.nombre = nombre;
       this.abreviatura = abreviatura;
       this.direccions = direccions;
       this.ciudads = ciudads;
    }
   
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }
    public Set<Ciudad> getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set<Ciudad> ciudads) {
        this.ciudads = ciudads;
    }




}


