package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Licenciaconducir generated by hbm2java
 */
public class Licenciaconducir  implements java.io.Serializable {


     private Integer idLicenciaConducir;
     private Chofer chofer;
     private Tipolicenciaconducir tipolicenciaconducir;
     private String clave;
     private Set<Renovacionlicenciaconducir> renovacionlicenciaconducirs = new HashSet<Renovacionlicenciaconducir>(0);

    public Licenciaconducir() {
    }

	
    public Licenciaconducir(Chofer chofer, Tipolicenciaconducir tipolicenciaconducir) {
        this.chofer = chofer;
        this.tipolicenciaconducir = tipolicenciaconducir;
    }
    public Licenciaconducir(Chofer chofer, Tipolicenciaconducir tipolicenciaconducir, String clave, Set<Renovacionlicenciaconducir> renovacionlicenciaconducirs) {
       this.chofer = chofer;
       this.tipolicenciaconducir = tipolicenciaconducir;
       this.clave = clave;
       this.renovacionlicenciaconducirs = renovacionlicenciaconducirs;
    }
   
    public Integer getIdLicenciaConducir() {
        return this.idLicenciaConducir;
    }
    
    public void setIdLicenciaConducir(Integer idLicenciaConducir) {
        this.idLicenciaConducir = idLicenciaConducir;
    }
    public Chofer getChofer() {
        return this.chofer;
    }
    
    public void setChofer(Chofer chofer) {
        this.chofer = chofer;
    }
    public Tipolicenciaconducir getTipolicenciaconducir() {
        return this.tipolicenciaconducir;
    }
    
    public void setTipolicenciaconducir(Tipolicenciaconducir tipolicenciaconducir) {
        this.tipolicenciaconducir = tipolicenciaconducir;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set<Renovacionlicenciaconducir> getRenovacionlicenciaconducirs() {
        return this.renovacionlicenciaconducirs;
    }
    
    public void setRenovacionlicenciaconducirs(Set<Renovacionlicenciaconducir> renovacionlicenciaconducirs) {
        this.renovacionlicenciaconducirs = renovacionlicenciaconducirs;
    }




}


