package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personafisica generated by hbm2java
 */
public class Personafisica  implements java.io.Serializable {


     private int idPersonaFisica;
     private Entidad entidad;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private Date fechaNacimiento;
     private Miembrofisico miembrofisico;

    public Personafisica() {
    }

	
    public Personafisica(int idPersonaFisica, Entidad entidad) {
        this.idPersonaFisica = idPersonaFisica;
        this.entidad = entidad;
    }
    public Personafisica(int idPersonaFisica, Entidad entidad, String nombre, String apellidoPaterno, String apellidoMaterno, Date fechaNacimiento, Miembrofisico miembrofisico) {
       this.idPersonaFisica = idPersonaFisica;
       this.entidad = entidad;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.fechaNacimiento = fechaNacimiento;
       this.miembrofisico = miembrofisico;
    }
   
    public int getIdPersonaFisica() {
        return this.idPersonaFisica;
    }
    
    public void setIdPersonaFisica(int idPersonaFisica) {
        this.idPersonaFisica = idPersonaFisica;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Miembrofisico getMiembrofisico() {
        return this.miembrofisico;
    }
    
    public void setMiembrofisico(Miembrofisico miembrofisico) {
        this.miembrofisico = miembrofisico;
    }

	@Override
	public String toString()
	{
		return "Personafisica{" + "idPersonaFisica=" + idPersonaFisica + ", entidad=" + entidad + ", nombre=" + nombre + ", apellidoPaterno=" + apellidoPaterno + ", apellidoMaterno=" + apellidoMaterno + ", fechaNacimiento=" + fechaNacimiento + ", miembrofisico=" + miembrofisico + '}';
	}

}


