package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA



/**
 * Personamoral generated by hbm2java
 */
public class Personamoral  implements java.io.Serializable {


     private Integer idPersonaMoral;
     private Agrupacionpersonas agrupacionpersonas;
     private Entidad entidad;
     private String razonSocial;

    public Personamoral() {
    }

	
    public Personamoral(Agrupacionpersonas agrupacionpersonas, Entidad entidad) {
        this.agrupacionpersonas = agrupacionpersonas;
        this.entidad = entidad;
    }
    public Personamoral(Agrupacionpersonas agrupacionpersonas, Entidad entidad, String razonSocial) {
       this.agrupacionpersonas = agrupacionpersonas;
       this.entidad = entidad;
       this.razonSocial = razonSocial;
    }
   
    public Integer getIdPersonaMoral() {
        return this.idPersonaMoral;
    }
    
    public void setIdPersonaMoral(Integer idPersonaMoral) {
        this.idPersonaMoral = idPersonaMoral;
    }
    public Agrupacionpersonas getAgrupacionpersonas() {
        return this.agrupacionpersonas;
    }
    
    public void setAgrupacionpersonas(Agrupacionpersonas agrupacionpersonas) {
        this.agrupacionpersonas = agrupacionpersonas;
    }
    public Entidad getEntidad() {
        return this.entidad;
    }
    
    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }




}


