package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA



/**
 * Placa generated by hbm2java
 */
public class Placa  implements java.io.Serializable {


     private int idPlaca;
     private Tipoplaca tipoplaca;
     private String numeroPlaca;

    public Placa() {
    }

	
    public Placa(int idPlaca, Tipoplaca tipoplaca) {
        this.idPlaca = idPlaca;
        this.tipoplaca = tipoplaca;
    }
    public Placa(int idPlaca, Tipoplaca tipoplaca, String numeroPlaca) {
       this.idPlaca = idPlaca;
       this.tipoplaca = tipoplaca;
       this.numeroPlaca = numeroPlaca;
    }
   
    public int getIdPlaca() {
        return this.idPlaca;
    }
    
    public void setIdPlaca(int idPlaca) {
        this.idPlaca = idPlaca;
    }
    public Tipoplaca getTipoplaca() {
        return this.tipoplaca;
    }
    
    public void setTipoplaca(Tipoplaca tipoplaca) {
        this.tipoplaca = tipoplaca;
    }
    public String getNumeroPlaca() {
        return this.numeroPlaca;
    }
    
    public void setNumeroPlaca(String numeroPlaca) {
        this.numeroPlaca = numeroPlaca;
    }




}


