package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Renovacionlicenciaconducir generated by hbm2java
 */
public class Renovacionlicenciaconducir  implements java.io.Serializable {


     private Integer idRenovacionLicenciaConducir;
     private Licenciaconducir licenciaconducir;
     private Estatuslicenciaconducir estatuslicenciaconducir;
     private Date fechaInicio;
     private Date fechaFin;

    public Renovacionlicenciaconducir() {
    }

	
    public Renovacionlicenciaconducir(Licenciaconducir licenciaconducir, Estatuslicenciaconducir estatuslicenciaconducir) {
        this.licenciaconducir = licenciaconducir;
        this.estatuslicenciaconducir = estatuslicenciaconducir;
    }
    public Renovacionlicenciaconducir(Licenciaconducir licenciaconducir, Estatuslicenciaconducir estatuslicenciaconducir, Date fechaInicio, Date fechaFin) {
       this.licenciaconducir = licenciaconducir;
       this.estatuslicenciaconducir = estatuslicenciaconducir;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getIdRenovacionLicenciaConducir() {
        return this.idRenovacionLicenciaConducir;
    }
    
    public void setIdRenovacionLicenciaConducir(Integer idRenovacionLicenciaConducir) {
        this.idRenovacionLicenciaConducir = idRenovacionLicenciaConducir;
    }
    public Licenciaconducir getLicenciaconducir() {
        return this.licenciaconducir;
    }
    
    public void setLicenciaconducir(Licenciaconducir licenciaconducir) {
        this.licenciaconducir = licenciaconducir;
    }
    public Estatuslicenciaconducir getEstatuslicenciaconducir() {
        return this.estatuslicenciaconducir;
    }
    
    public void setEstatuslicenciaconducir(Estatuslicenciaconducir estatuslicenciaconducir) {
        this.estatuslicenciaconducir = estatuslicenciaconducir;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


