package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipodireccion generated by hbm2java
 */
public class Tipodireccion  implements java.io.Serializable {


     private int idTipoDireccion;
     private String nombreTipo;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Tipodireccion() {
    }

	
    public Tipodireccion(int idTipoDireccion) {
        this.idTipoDireccion = idTipoDireccion;
    }
    public Tipodireccion(int idTipoDireccion, String nombreTipo, Set<Direccion> direccions) {
       this.idTipoDireccion = idTipoDireccion;
       this.nombreTipo = nombreTipo;
       this.direccions = direccions;
    }
   
    public int getIdTipoDireccion() {
        return this.idTipoDireccion;
    }
    
    public void setIdTipoDireccion(int idTipoDireccion) {
        this.idTipoDireccion = idTipoDireccion;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


