package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipomime generated by hbm2java
 */
public class Tipomime  implements java.io.Serializable {


     private int idTipoMime;
     private String nombre;
     private String descripcion;
     private Set<Archivo> archivos = new HashSet<Archivo>(0);

    public Tipomime() {
    }

	
    public Tipomime(int idTipoMime, String nombre) {
        this.idTipoMime = idTipoMime;
        this.nombre = nombre;
    }
    public Tipomime(int idTipoMime, String nombre, String descripcion, Set<Archivo> archivos) {
       this.idTipoMime = idTipoMime;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.archivos = archivos;
    }
   
    public int getIdTipoMime() {
        return this.idTipoMime;
    }
    
    public void setIdTipoMime(int idTipoMime) {
        this.idTipoMime = idTipoMime;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Archivo> getArchivos() {
        return this.archivos;
    }
    
    public void setArchivos(Set<Archivo> archivos) {
        this.archivos = archivos;
    }




}


