package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoarchivo generated by hbm2java
 */
public class Tipoarchivo  implements java.io.Serializable {


     private int idTipoArchivo;
     private String nombre;
     private Set<Archivo> archivos = new HashSet<Archivo>(0);

    public Tipoarchivo() {
    }

	
    public Tipoarchivo(int idTipoArchivo, String nombre) {
        this.idTipoArchivo = idTipoArchivo;
        this.nombre = nombre;
    }
    public Tipoarchivo(int idTipoArchivo, String nombre, Set<Archivo> archivos) {
       this.idTipoArchivo = idTipoArchivo;
       this.nombre = nombre;
       this.archivos = archivos;
    }
   
    public int getIdTipoArchivo() {
        return this.idTipoArchivo;
    }
    
    public void setIdTipoArchivo(int idTipoArchivo) {
        this.idTipoArchivo = idTipoArchivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Archivo> getArchivos() {
        return this.archivos;
    }
    
    public void setArchivos(Set<Archivo> archivos) {
        this.archivos = archivos;
    }




}


