package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoplaca generated by hbm2java
 */
public class Tipoplaca  implements java.io.Serializable {


     private int idTipoPlaca;
     private String nombre;
     private Set<Placa> placas = new HashSet<Placa>(0);

    public Tipoplaca() {
    }

	
    public Tipoplaca(int idTipoPlaca) {
        this.idTipoPlaca = idTipoPlaca;
    }
    public Tipoplaca(int idTipoPlaca, String nombre, Set<Placa> placas) {
       this.idTipoPlaca = idTipoPlaca;
       this.nombre = nombre;
       this.placas = placas;
    }
   
    public int getIdTipoPlaca() {
        return this.idTipoPlaca;
    }
    
    public void setIdTipoPlaca(int idTipoPlaca) {
        this.idTipoPlaca = idTipoPlaca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Placa> getPlacas() {
        return this.placas;
    }
    
    public void setPlacas(Set<Placa> placas) {
        this.placas = placas;
    }




}


