package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipolicenciaconducir generated by hbm2java
 */
public class Tipolicenciaconducir  implements java.io.Serializable {


     private Integer idTipoLicenciaConducir;
     private String nombre;
     private Set<Licenciaconducir> licenciaconducirs = new HashSet<Licenciaconducir>(0);

    public Tipolicenciaconducir() {
    }

    public Tipolicenciaconducir(String nombre, Set<Licenciaconducir> licenciaconducirs) {
       this.nombre = nombre;
       this.licenciaconducirs = licenciaconducirs;
    }
   
    public Integer getIdTipoLicenciaConducir() {
        return this.idTipoLicenciaConducir;
    }
    
    public void setIdTipoLicenciaConducir(Integer idTipoLicenciaConducir) {
        this.idTipoLicenciaConducir = idTipoLicenciaConducir;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Licenciaconducir> getLicenciaconducirs() {
        return this.licenciaconducirs;
    }
    
    public void setLicenciaconducirs(Set<Licenciaconducir> licenciaconducirs) {
        this.licenciaconducirs = licenciaconducirs;
    }




}


