package mx.com.magmasoft.satp.model;
// Generated 02-sep-2012 14:15:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipotelefono generated by hbm2java
 */
public class Tipotelefono  implements java.io.Serializable {


     private int idTipoTelefono;
     private String nombre;
     private Set<Telefono> telefonos = new HashSet<Telefono>(0);

    public Tipotelefono() {
    }

	
    public Tipotelefono(int idTipoTelefono) {
        this.idTipoTelefono = idTipoTelefono;
    }
    public Tipotelefono(int idTipoTelefono, String nombre, Set<Telefono> telefonos) {
       this.idTipoTelefono = idTipoTelefono;
       this.nombre = nombre;
       this.telefonos = telefonos;
    }
   
    public int getIdTipoTelefono() {
        return this.idTipoTelefono;
    }
    
    public void setIdTipoTelefono(int idTipoTelefono) {
        this.idTipoTelefono = idTipoTelefono;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Telefono> getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }




}


